import { NavBar, PageNav } from "../Components";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`flex h-screen w-screen ${inter.className}`}>
        <NavBar />
        <div className="flex h-full w-4/5 p-2 items-center justify-center">
          <div className="flex h-full w-full overflow-hidden   bg-white rounded-lg flex-col items-center text-black">
              {children}
            {/* <PageNav pageTitle=""/>
            <div className="flex w-full h-full justify-center items-cente rounded-lg p-2">
            </div> */}
          </div>
        </div>
      </body>
    </html>
  );
}
