const staticParticipants = [
  {
    id: "1",
    name: "John Doe",
    email: "john.doe@example.com",
    gender: "Male",
    country: "United States",
    role: "Developer",
    attendance: 50,
  },
  {
    id: "2",
    name: "Jane Smith",
    email: "jane.smith@example.com",
    gender: "Female",
    country: "Canada",
    role: "Designer",
    attendance: 60,
  },
  {
    id: "3",
    name: "Mike Johnson",
    email: "mike.johnson@example.com",
    gender: "Male",
    country: "United Kingdom",
    role: "Product Manager",
    attendance: 70,
  },
  {
    id: "4",
    name: "Sarah Williams",
    email: "sarah.williams@example.com",
    gender: "Female",
    country: "Australia",
    role: "Data Scientist",
    attendance: 10,
  },
  {
    id: "5",
    name: "David Brown",
    email: "david.brown@example.com",
    gender: "Male",
    country: "Germany",
    role: "Marketing Specialist",
    attendance: 50,
  },
  {
    id: "6",
    name: "David Brown",
    email: "david.brown@example.com",
    gender: "Male",
    country: "Germany",
    role: "Marketing Specialist",
    attendance: 50,
  },
  {
    id: "7",
    name: "David Brown",
    email: "david.brown@example.com",
    gender: "Male",
    country: "Germany",
    role: "Marketing Specialist",
    attendance: 100,
  },
  {
    id: "8",
    name: "David Brown",
    email: "david.brown@example.com",
    gender: "Male",
    country: "Germany",
    role: "Marketing Specialist",
    attendance: 50,
  },
  {
    id: "9",
    name: "David Brown",
    email: "david.brown@example.com",
    gender: "Male",
    country: "Germany",
    role: "Marketing Specialist",
    attendance: 50,
  },
  {
    id: "10",
    name: "David Brown",
    email: "david.brown@example.com",
    gender: "Male",
    country: "Germany",
    role: "Marketing Specialist",
    attendance: 50,
  },{
    id: "11",
    name: "David Brown",
    email: "david.brown@example.com",
    gender: "Male",
    country: "Germany",
    role: "Marketing Specialist",
    attendance: 50,
  },
  {
    id: "12",
    name: "David Brown",
    email: "david.brown@example.com",
    gender: "Male",
    country: "Germany",
    role: "Marketing Specialist",
    attendance: 50,
  },
];

export default staticParticipants;
